# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_water_mainwd(object):
    def setupUi(self, water_mainwd):
        if not water_mainwd.objectName():
            water_mainwd.setObjectName(u"water_mainwd")
        water_mainwd.resize(1000, 822)
        water_mainwd.setContextMenuPolicy(Qt.DefaultContextMenu)
        water_mainwd.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(water_mainwd)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sel_log_btn = QPushButton(self.centralwidget)
        self.sel_log_btn.setObjectName(u"sel_log_btn")
        self.sel_log_btn.setGeometry(QRect(120, 10, 21, 28))
        self.sel_log_lbl = QLineEdit(self.centralwidget)
        self.sel_log_lbl.setObjectName(u"sel_log_lbl")
        self.sel_log_lbl.setGeometry(QRect(160, 10, 771, 21))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 10, 81, 21))
        self.sel_tab_btn = QPushButton(self.centralwidget)
        self.sel_tab_btn.setObjectName(u"sel_tab_btn")
        self.sel_tab_btn.setGeometry(QRect(120, 50, 21, 28))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 50, 81, 21))
        self.sel_tab_lbl = QLineEdit(self.centralwidget)
        self.sel_tab_lbl.setObjectName(u"sel_tab_lbl")
        self.sel_tab_lbl.setGeometry(QRect(160, 50, 771, 21))
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(70, 160, 81, 21))
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(400, 160, 81, 21))
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(750, 160, 81, 21))
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 90, 81, 21))
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 120, 81, 21))
        self.start_filter = QLineEdit(self.centralwidget)
        self.start_filter.setObjectName(u"start_filter")
        self.start_filter.setGeometry(QRect(120, 90, 511, 21))
        self.end_filter = QLineEdit(self.centralwidget)
        self.end_filter.setObjectName(u"end_filter")
        self.end_filter.setGeometry(QRect(120, 120, 511, 21))
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(840, 160, 111, 21))
        self.load_setting_btn = QPushButton(self.centralwidget)
        self.load_setting_btn.setObjectName(u"load_setting_btn")
        self.load_setting_btn.setGeometry(QRect(710, 90, 71, 28))
        self.dump_setting_btn = QPushButton(self.centralwidget)
        self.dump_setting_btn.setObjectName(u"dump_setting_btn")
        self.dump_setting_btn.setGeometry(QRect(820, 90, 71, 28))
        self.result_lbl = QTextBrowser(self.centralwidget)
        self.result_lbl.setObjectName(u"result_lbl")
        self.result_lbl.setGeometry(QRect(20, 690, 901, 81))
        self.exec_btn = QPushButton(self.centralwidget)
        self.exec_btn.setObjectName(u"exec_btn")
        self.exec_btn.setGeometry(QRect(930, 690, 61, 71))
        self.clear_output_btn = QPushButton(self.centralwidget)
        self.clear_output_btn.setObjectName(u"clear_output_btn")
        self.clear_output_btn.setGeometry(QRect(940, 650, 51, 31))
        self.clear_input_btn = QPushButton(self.centralwidget)
        self.clear_input_btn.setObjectName(u"clear_input_btn")
        self.clear_input_btn.setGeometry(QRect(940, 190, 51, 51))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 180, 911, 501))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.frame_15 = QFrame(self.tab)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(0, 420, 911, 31))
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.item_name_15 = QLineEdit(self.frame_15)
        self.item_name_15.setObjectName(u"item_name_15")
        self.item_name_15.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_15 = QLineEdit(self.frame_15)
        self.item_reg_15.setObjectName(u"item_reg_15")
        self.item_reg_15.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_15 = QLineEdit(self.frame_15)
        self.item_index_15.setObjectName(u"item_index_15")
        self.item_index_15.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_15 = QLineEdit(self.frame_15)
        self.item_skip_15.setObjectName(u"item_skip_15")
        self.item_skip_15.setGeometry(QRect(840, 0, 61, 21))
        self.frame_6 = QFrame(self.tab)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(0, 150, 911, 31))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.item_name_6 = QLineEdit(self.frame_6)
        self.item_name_6.setObjectName(u"item_name_6")
        self.item_name_6.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_6 = QLineEdit(self.frame_6)
        self.item_reg_6.setObjectName(u"item_reg_6")
        self.item_reg_6.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_6 = QLineEdit(self.frame_6)
        self.item_index_6.setObjectName(u"item_index_6")
        self.item_index_6.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_6 = QLineEdit(self.frame_6)
        self.item_skip_6.setObjectName(u"item_skip_6")
        self.item_skip_6.setGeometry(QRect(840, 0, 61, 21))
        self.frame_16 = QFrame(self.tab)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setGeometry(QRect(0, 450, 911, 31))
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.item_name_16 = QLineEdit(self.frame_16)
        self.item_name_16.setObjectName(u"item_name_16")
        self.item_name_16.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_16 = QLineEdit(self.frame_16)
        self.item_reg_16.setObjectName(u"item_reg_16")
        self.item_reg_16.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_16 = QLineEdit(self.frame_16)
        self.item_index_16.setObjectName(u"item_index_16")
        self.item_index_16.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_16 = QLineEdit(self.frame_16)
        self.item_skip_16.setObjectName(u"item_skip_16")
        self.item_skip_16.setGeometry(QRect(840, 0, 61, 21))
        self.frame_9 = QFrame(self.tab)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(0, 240, 911, 31))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.item_name_9 = QLineEdit(self.frame_9)
        self.item_name_9.setObjectName(u"item_name_9")
        self.item_name_9.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_9 = QLineEdit(self.frame_9)
        self.item_reg_9.setObjectName(u"item_reg_9")
        self.item_reg_9.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_9 = QLineEdit(self.frame_9)
        self.item_index_9.setObjectName(u"item_index_9")
        self.item_index_9.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_9 = QLineEdit(self.frame_9)
        self.item_skip_9.setObjectName(u"item_skip_9")
        self.item_skip_9.setGeometry(QRect(840, 0, 61, 21))
        self.frame_11 = QFrame(self.tab)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(0, 300, 911, 31))
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.item_name_11 = QLineEdit(self.frame_11)
        self.item_name_11.setObjectName(u"item_name_11")
        self.item_name_11.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_11 = QLineEdit(self.frame_11)
        self.item_reg_11.setObjectName(u"item_reg_11")
        self.item_reg_11.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_11 = QLineEdit(self.frame_11)
        self.item_index_11.setObjectName(u"item_index_11")
        self.item_index_11.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_11 = QLineEdit(self.frame_11)
        self.item_skip_11.setObjectName(u"item_skip_11")
        self.item_skip_11.setGeometry(QRect(840, 0, 61, 21))
        self.frame = QFrame(self.tab)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 0, 911, 31))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.item_name_1 = QLineEdit(self.frame)
        self.item_name_1.setObjectName(u"item_name_1")
        self.item_name_1.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_1 = QLineEdit(self.frame)
        self.item_reg_1.setObjectName(u"item_reg_1")
        self.item_reg_1.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_1 = QLineEdit(self.frame)
        self.item_index_1.setObjectName(u"item_index_1")
        self.item_index_1.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_1 = QLineEdit(self.frame)
        self.item_skip_1.setObjectName(u"item_skip_1")
        self.item_skip_1.setGeometry(QRect(840, 0, 61, 21))
        self.frame_4 = QFrame(self.tab)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(0, 90, 911, 31))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.item_name_4 = QLineEdit(self.frame_4)
        self.item_name_4.setObjectName(u"item_name_4")
        self.item_name_4.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_4 = QLineEdit(self.frame_4)
        self.item_reg_4.setObjectName(u"item_reg_4")
        self.item_reg_4.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_4 = QLineEdit(self.frame_4)
        self.item_index_4.setObjectName(u"item_index_4")
        self.item_index_4.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_4 = QLineEdit(self.frame_4)
        self.item_skip_4.setObjectName(u"item_skip_4")
        self.item_skip_4.setGeometry(QRect(840, 0, 61, 21))
        self.frame_5 = QFrame(self.tab)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(0, 120, 911, 31))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.item_name_5 = QLineEdit(self.frame_5)
        self.item_name_5.setObjectName(u"item_name_5")
        self.item_name_5.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_5 = QLineEdit(self.frame_5)
        self.item_reg_5.setObjectName(u"item_reg_5")
        self.item_reg_5.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_5 = QLineEdit(self.frame_5)
        self.item_index_5.setObjectName(u"item_index_5")
        self.item_index_5.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_5 = QLineEdit(self.frame_5)
        self.item_skip_5.setObjectName(u"item_skip_5")
        self.item_skip_5.setGeometry(QRect(840, 0, 61, 21))
        self.frame_7 = QFrame(self.tab)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(0, 180, 911, 31))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.item_name_7 = QLineEdit(self.frame_7)
        self.item_name_7.setObjectName(u"item_name_7")
        self.item_name_7.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_7 = QLineEdit(self.frame_7)
        self.item_reg_7.setObjectName(u"item_reg_7")
        self.item_reg_7.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_7 = QLineEdit(self.frame_7)
        self.item_index_7.setObjectName(u"item_index_7")
        self.item_index_7.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_7 = QLineEdit(self.frame_7)
        self.item_skip_7.setObjectName(u"item_skip_7")
        self.item_skip_7.setGeometry(QRect(840, 0, 61, 21))
        self.frame_12 = QFrame(self.tab)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(0, 330, 911, 31))
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.item_name_12 = QLineEdit(self.frame_12)
        self.item_name_12.setObjectName(u"item_name_12")
        self.item_name_12.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_12 = QLineEdit(self.frame_12)
        self.item_reg_12.setObjectName(u"item_reg_12")
        self.item_reg_12.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_12 = QLineEdit(self.frame_12)
        self.item_index_12.setObjectName(u"item_index_12")
        self.item_index_12.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_12 = QLineEdit(self.frame_12)
        self.item_skip_12.setObjectName(u"item_skip_12")
        self.item_skip_12.setGeometry(QRect(840, 0, 61, 21))
        self.frame_10 = QFrame(self.tab)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(0, 270, 911, 31))
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.item_name_10 = QLineEdit(self.frame_10)
        self.item_name_10.setObjectName(u"item_name_10")
        self.item_name_10.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_10 = QLineEdit(self.frame_10)
        self.item_reg_10.setObjectName(u"item_reg_10")
        self.item_reg_10.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_10 = QLineEdit(self.frame_10)
        self.item_index_10.setObjectName(u"item_index_10")
        self.item_index_10.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_10 = QLineEdit(self.frame_10)
        self.item_skip_10.setObjectName(u"item_skip_10")
        self.item_skip_10.setGeometry(QRect(840, 0, 61, 21))
        self.frame_14 = QFrame(self.tab)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(0, 390, 911, 31))
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.item_name_14 = QLineEdit(self.frame_14)
        self.item_name_14.setObjectName(u"item_name_14")
        self.item_name_14.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_14 = QLineEdit(self.frame_14)
        self.item_reg_14.setObjectName(u"item_reg_14")
        self.item_reg_14.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_14 = QLineEdit(self.frame_14)
        self.item_index_14.setObjectName(u"item_index_14")
        self.item_index_14.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_14 = QLineEdit(self.frame_14)
        self.item_skip_14.setObjectName(u"item_skip_14")
        self.item_skip_14.setGeometry(QRect(840, 0, 61, 21))
        self.frame_3 = QFrame(self.tab)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 60, 911, 31))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.item_name_3 = QLineEdit(self.frame_3)
        self.item_name_3.setObjectName(u"item_name_3")
        self.item_name_3.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_3 = QLineEdit(self.frame_3)
        self.item_reg_3.setObjectName(u"item_reg_3")
        self.item_reg_3.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_3 = QLineEdit(self.frame_3)
        self.item_index_3.setObjectName(u"item_index_3")
        self.item_index_3.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_3 = QLineEdit(self.frame_3)
        self.item_skip_3.setObjectName(u"item_skip_3")
        self.item_skip_3.setGeometry(QRect(840, 0, 61, 21))
        self.frame_13 = QFrame(self.tab)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(0, 360, 911, 31))
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.item_name_13 = QLineEdit(self.frame_13)
        self.item_name_13.setObjectName(u"item_name_13")
        self.item_name_13.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_13 = QLineEdit(self.frame_13)
        self.item_reg_13.setObjectName(u"item_reg_13")
        self.item_reg_13.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_13 = QLineEdit(self.frame_13)
        self.item_index_13.setObjectName(u"item_index_13")
        self.item_index_13.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_13 = QLineEdit(self.frame_13)
        self.item_skip_13.setObjectName(u"item_skip_13")
        self.item_skip_13.setGeometry(QRect(840, 0, 61, 21))
        self.frame_2 = QFrame(self.tab)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(0, 30, 911, 31))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.item_name_2 = QLineEdit(self.frame_2)
        self.item_name_2.setObjectName(u"item_name_2")
        self.item_name_2.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_2 = QLineEdit(self.frame_2)
        self.item_reg_2.setObjectName(u"item_reg_2")
        self.item_reg_2.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_2 = QLineEdit(self.frame_2)
        self.item_index_2.setObjectName(u"item_index_2")
        self.item_index_2.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_2 = QLineEdit(self.frame_2)
        self.item_skip_2.setObjectName(u"item_skip_2")
        self.item_skip_2.setGeometry(QRect(840, 0, 61, 21))
        self.frame_8 = QFrame(self.tab)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(0, 210, 911, 31))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.item_name_8 = QLineEdit(self.frame_8)
        self.item_name_8.setObjectName(u"item_name_8")
        self.item_name_8.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_8 = QLineEdit(self.frame_8)
        self.item_reg_8.setObjectName(u"item_reg_8")
        self.item_reg_8.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_8 = QLineEdit(self.frame_8)
        self.item_index_8.setObjectName(u"item_index_8")
        self.item_index_8.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_8 = QLineEdit(self.frame_8)
        self.item_skip_8.setObjectName(u"item_skip_8")
        self.item_skip_8.setGeometry(QRect(840, 0, 61, 21))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.frame_17 = QFrame(self.tab_2)
        self.frame_17.setObjectName(u"frame_17")
        self.frame_17.setGeometry(QRect(0, 0, 911, 31))
        self.frame_17.setFrameShape(QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QFrame.Raised)
        self.item_name_17 = QLineEdit(self.frame_17)
        self.item_name_17.setObjectName(u"item_name_17")
        self.item_name_17.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_17 = QLineEdit(self.frame_17)
        self.item_reg_17.setObjectName(u"item_reg_17")
        self.item_reg_17.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_17 = QLineEdit(self.frame_17)
        self.item_index_17.setObjectName(u"item_index_17")
        self.item_index_17.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_17 = QLineEdit(self.frame_17)
        self.item_skip_17.setObjectName(u"item_skip_17")
        self.item_skip_17.setGeometry(QRect(840, 0, 61, 21))
        self.frame_18 = QFrame(self.tab_2)
        self.frame_18.setObjectName(u"frame_18")
        self.frame_18.setGeometry(QRect(0, 30, 911, 31))
        self.frame_18.setFrameShape(QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QFrame.Raised)
        self.item_name_18 = QLineEdit(self.frame_18)
        self.item_name_18.setObjectName(u"item_name_18")
        self.item_name_18.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_18 = QLineEdit(self.frame_18)
        self.item_reg_18.setObjectName(u"item_reg_18")
        self.item_reg_18.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_18 = QLineEdit(self.frame_18)
        self.item_index_18.setObjectName(u"item_index_18")
        self.item_index_18.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_18 = QLineEdit(self.frame_18)
        self.item_skip_18.setObjectName(u"item_skip_18")
        self.item_skip_18.setGeometry(QRect(840, 0, 61, 21))
        self.frame_19 = QFrame(self.tab_2)
        self.frame_19.setObjectName(u"frame_19")
        self.frame_19.setGeometry(QRect(0, 60, 911, 31))
        self.frame_19.setFrameShape(QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QFrame.Raised)
        self.item_name_19 = QLineEdit(self.frame_19)
        self.item_name_19.setObjectName(u"item_name_19")
        self.item_name_19.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_19 = QLineEdit(self.frame_19)
        self.item_reg_19.setObjectName(u"item_reg_19")
        self.item_reg_19.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_19 = QLineEdit(self.frame_19)
        self.item_index_19.setObjectName(u"item_index_19")
        self.item_index_19.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_19 = QLineEdit(self.frame_19)
        self.item_skip_19.setObjectName(u"item_skip_19")
        self.item_skip_19.setGeometry(QRect(840, 0, 61, 21))
        self.frame_20 = QFrame(self.tab_2)
        self.frame_20.setObjectName(u"frame_20")
        self.frame_20.setGeometry(QRect(0, 90, 911, 31))
        self.frame_20.setFrameShape(QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QFrame.Raised)
        self.item_name_20 = QLineEdit(self.frame_20)
        self.item_name_20.setObjectName(u"item_name_20")
        self.item_name_20.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_20 = QLineEdit(self.frame_20)
        self.item_reg_20.setObjectName(u"item_reg_20")
        self.item_reg_20.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_20 = QLineEdit(self.frame_20)
        self.item_index_20.setObjectName(u"item_index_20")
        self.item_index_20.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_20 = QLineEdit(self.frame_20)
        self.item_skip_20.setObjectName(u"item_skip_20")
        self.item_skip_20.setGeometry(QRect(840, 0, 61, 21))
        self.frame_21 = QFrame(self.tab_2)
        self.frame_21.setObjectName(u"frame_21")
        self.frame_21.setGeometry(QRect(0, 120, 911, 31))
        self.frame_21.setFrameShape(QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QFrame.Raised)
        self.item_name_21 = QLineEdit(self.frame_21)
        self.item_name_21.setObjectName(u"item_name_21")
        self.item_name_21.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_21 = QLineEdit(self.frame_21)
        self.item_reg_21.setObjectName(u"item_reg_21")
        self.item_reg_21.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_21 = QLineEdit(self.frame_21)
        self.item_index_21.setObjectName(u"item_index_21")
        self.item_index_21.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_21 = QLineEdit(self.frame_21)
        self.item_skip_21.setObjectName(u"item_skip_21")
        self.item_skip_21.setGeometry(QRect(840, 0, 61, 21))
        self.frame_22 = QFrame(self.tab_2)
        self.frame_22.setObjectName(u"frame_22")
        self.frame_22.setGeometry(QRect(0, 150, 911, 31))
        self.frame_22.setFrameShape(QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QFrame.Raised)
        self.item_name_22 = QLineEdit(self.frame_22)
        self.item_name_22.setObjectName(u"item_name_22")
        self.item_name_22.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_22 = QLineEdit(self.frame_22)
        self.item_reg_22.setObjectName(u"item_reg_22")
        self.item_reg_22.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_22 = QLineEdit(self.frame_22)
        self.item_index_22.setObjectName(u"item_index_22")
        self.item_index_22.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_22 = QLineEdit(self.frame_22)
        self.item_skip_22.setObjectName(u"item_skip_22")
        self.item_skip_22.setGeometry(QRect(840, 0, 61, 21))
        self.frame_23 = QFrame(self.tab_2)
        self.frame_23.setObjectName(u"frame_23")
        self.frame_23.setGeometry(QRect(0, 180, 911, 31))
        self.frame_23.setFrameShape(QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QFrame.Raised)
        self.item_name_23 = QLineEdit(self.frame_23)
        self.item_name_23.setObjectName(u"item_name_23")
        self.item_name_23.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_23 = QLineEdit(self.frame_23)
        self.item_reg_23.setObjectName(u"item_reg_23")
        self.item_reg_23.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_23 = QLineEdit(self.frame_23)
        self.item_index_23.setObjectName(u"item_index_23")
        self.item_index_23.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_23 = QLineEdit(self.frame_23)
        self.item_skip_23.setObjectName(u"item_skip_23")
        self.item_skip_23.setGeometry(QRect(840, 0, 61, 21))
        self.frame_24 = QFrame(self.tab_2)
        self.frame_24.setObjectName(u"frame_24")
        self.frame_24.setGeometry(QRect(0, 210, 911, 31))
        self.frame_24.setFrameShape(QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QFrame.Raised)
        self.item_name_24 = QLineEdit(self.frame_24)
        self.item_name_24.setObjectName(u"item_name_24")
        self.item_name_24.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_24 = QLineEdit(self.frame_24)
        self.item_reg_24.setObjectName(u"item_reg_24")
        self.item_reg_24.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_24 = QLineEdit(self.frame_24)
        self.item_index_24.setObjectName(u"item_index_24")
        self.item_index_24.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_24 = QLineEdit(self.frame_24)
        self.item_skip_24.setObjectName(u"item_skip_24")
        self.item_skip_24.setGeometry(QRect(840, 0, 61, 21))
        self.frame_25 = QFrame(self.tab_2)
        self.frame_25.setObjectName(u"frame_25")
        self.frame_25.setGeometry(QRect(0, 240, 911, 31))
        self.frame_25.setFrameShape(QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QFrame.Raised)
        self.item_name_25 = QLineEdit(self.frame_25)
        self.item_name_25.setObjectName(u"item_name_25")
        self.item_name_25.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_25 = QLineEdit(self.frame_25)
        self.item_reg_25.setObjectName(u"item_reg_25")
        self.item_reg_25.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_25 = QLineEdit(self.frame_25)
        self.item_index_25.setObjectName(u"item_index_25")
        self.item_index_25.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_25 = QLineEdit(self.frame_25)
        self.item_skip_25.setObjectName(u"item_skip_25")
        self.item_skip_25.setGeometry(QRect(840, 0, 61, 21))
        self.frame_26 = QFrame(self.tab_2)
        self.frame_26.setObjectName(u"frame_26")
        self.frame_26.setGeometry(QRect(0, 270, 911, 31))
        self.frame_26.setFrameShape(QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QFrame.Raised)
        self.item_name_26 = QLineEdit(self.frame_26)
        self.item_name_26.setObjectName(u"item_name_26")
        self.item_name_26.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_26 = QLineEdit(self.frame_26)
        self.item_reg_26.setObjectName(u"item_reg_26")
        self.item_reg_26.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_26 = QLineEdit(self.frame_26)
        self.item_index_26.setObjectName(u"item_index_26")
        self.item_index_26.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_26 = QLineEdit(self.frame_26)
        self.item_skip_26.setObjectName(u"item_skip_26")
        self.item_skip_26.setGeometry(QRect(840, 0, 61, 21))
        self.frame_27 = QFrame(self.tab_2)
        self.frame_27.setObjectName(u"frame_27")
        self.frame_27.setGeometry(QRect(0, 300, 911, 31))
        self.frame_27.setFrameShape(QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QFrame.Raised)
        self.item_name_27 = QLineEdit(self.frame_27)
        self.item_name_27.setObjectName(u"item_name_27")
        self.item_name_27.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_27 = QLineEdit(self.frame_27)
        self.item_reg_27.setObjectName(u"item_reg_27")
        self.item_reg_27.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_27 = QLineEdit(self.frame_27)
        self.item_index_27.setObjectName(u"item_index_27")
        self.item_index_27.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_27 = QLineEdit(self.frame_27)
        self.item_skip_27.setObjectName(u"item_skip_27")
        self.item_skip_27.setGeometry(QRect(840, 0, 61, 21))
        self.frame_28 = QFrame(self.tab_2)
        self.frame_28.setObjectName(u"frame_28")
        self.frame_28.setGeometry(QRect(0, 330, 911, 31))
        self.frame_28.setFrameShape(QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QFrame.Raised)
        self.item_name_28 = QLineEdit(self.frame_28)
        self.item_name_28.setObjectName(u"item_name_28")
        self.item_name_28.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_28 = QLineEdit(self.frame_28)
        self.item_reg_28.setObjectName(u"item_reg_28")
        self.item_reg_28.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_28 = QLineEdit(self.frame_28)
        self.item_index_28.setObjectName(u"item_index_28")
        self.item_index_28.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_28 = QLineEdit(self.frame_28)
        self.item_skip_28.setObjectName(u"item_skip_28")
        self.item_skip_28.setGeometry(QRect(840, 0, 61, 21))
        self.frame_29 = QFrame(self.tab_2)
        self.frame_29.setObjectName(u"frame_29")
        self.frame_29.setGeometry(QRect(0, 360, 911, 31))
        self.frame_29.setFrameShape(QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QFrame.Raised)
        self.item_name_29 = QLineEdit(self.frame_29)
        self.item_name_29.setObjectName(u"item_name_29")
        self.item_name_29.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_29 = QLineEdit(self.frame_29)
        self.item_reg_29.setObjectName(u"item_reg_29")
        self.item_reg_29.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_29 = QLineEdit(self.frame_29)
        self.item_index_29.setObjectName(u"item_index_29")
        self.item_index_29.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_29 = QLineEdit(self.frame_29)
        self.item_skip_29.setObjectName(u"item_skip_29")
        self.item_skip_29.setGeometry(QRect(840, 0, 61, 21))
        self.frame_30 = QFrame(self.tab_2)
        self.frame_30.setObjectName(u"frame_30")
        self.frame_30.setGeometry(QRect(0, 390, 911, 31))
        self.frame_30.setFrameShape(QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QFrame.Raised)
        self.item_name_30 = QLineEdit(self.frame_30)
        self.item_name_30.setObjectName(u"item_name_30")
        self.item_name_30.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_30 = QLineEdit(self.frame_30)
        self.item_reg_30.setObjectName(u"item_reg_30")
        self.item_reg_30.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_30 = QLineEdit(self.frame_30)
        self.item_index_30.setObjectName(u"item_index_30")
        self.item_index_30.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_30 = QLineEdit(self.frame_30)
        self.item_skip_30.setObjectName(u"item_skip_30")
        self.item_skip_30.setGeometry(QRect(840, 0, 61, 21))
        self.frame_31 = QFrame(self.tab_2)
        self.frame_31.setObjectName(u"frame_31")
        self.frame_31.setGeometry(QRect(0, 420, 911, 31))
        self.frame_31.setFrameShape(QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QFrame.Raised)
        self.item_name_31 = QLineEdit(self.frame_31)
        self.item_name_31.setObjectName(u"item_name_31")
        self.item_name_31.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_31 = QLineEdit(self.frame_31)
        self.item_reg_31.setObjectName(u"item_reg_31")
        self.item_reg_31.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_31 = QLineEdit(self.frame_31)
        self.item_index_31.setObjectName(u"item_index_31")
        self.item_index_31.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_31 = QLineEdit(self.frame_31)
        self.item_skip_31.setObjectName(u"item_skip_31")
        self.item_skip_31.setGeometry(QRect(840, 0, 61, 21))
        self.frame_32 = QFrame(self.tab_2)
        self.frame_32.setObjectName(u"frame_32")
        self.frame_32.setGeometry(QRect(0, 450, 911, 31))
        self.frame_32.setFrameShape(QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QFrame.Raised)
        self.item_name_32 = QLineEdit(self.frame_32)
        self.item_name_32.setObjectName(u"item_name_32")
        self.item_name_32.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_32 = QLineEdit(self.frame_32)
        self.item_reg_32.setObjectName(u"item_reg_32")
        self.item_reg_32.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_32 = QLineEdit(self.frame_32)
        self.item_index_32.setObjectName(u"item_index_32")
        self.item_index_32.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_32 = QLineEdit(self.frame_32)
        self.item_skip_32.setObjectName(u"item_skip_32")
        self.item_skip_32.setGeometry(QRect(840, 0, 61, 21))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.frame_33 = QFrame(self.tab_3)
        self.frame_33.setObjectName(u"frame_33")
        self.frame_33.setGeometry(QRect(0, 0, 911, 31))
        self.frame_33.setFrameShape(QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QFrame.Raised)
        self.item_name_33 = QLineEdit(self.frame_33)
        self.item_name_33.setObjectName(u"item_name_33")
        self.item_name_33.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_33 = QLineEdit(self.frame_33)
        self.item_reg_33.setObjectName(u"item_reg_33")
        self.item_reg_33.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_33 = QLineEdit(self.frame_33)
        self.item_index_33.setObjectName(u"item_index_33")
        self.item_index_33.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_33 = QLineEdit(self.frame_33)
        self.item_skip_33.setObjectName(u"item_skip_33")
        self.item_skip_33.setGeometry(QRect(840, 0, 61, 21))
        self.frame_34 = QFrame(self.tab_3)
        self.frame_34.setObjectName(u"frame_34")
        self.frame_34.setGeometry(QRect(0, 30, 911, 31))
        self.frame_34.setFrameShape(QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QFrame.Raised)
        self.item_name_34 = QLineEdit(self.frame_34)
        self.item_name_34.setObjectName(u"item_name_34")
        self.item_name_34.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_34 = QLineEdit(self.frame_34)
        self.item_reg_34.setObjectName(u"item_reg_34")
        self.item_reg_34.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_34 = QLineEdit(self.frame_34)
        self.item_index_34.setObjectName(u"item_index_34")
        self.item_index_34.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_34 = QLineEdit(self.frame_34)
        self.item_skip_34.setObjectName(u"item_skip_34")
        self.item_skip_34.setGeometry(QRect(840, 0, 61, 21))
        self.frame_35 = QFrame(self.tab_3)
        self.frame_35.setObjectName(u"frame_35")
        self.frame_35.setGeometry(QRect(0, 60, 911, 31))
        self.frame_35.setFrameShape(QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QFrame.Raised)
        self.item_name_35 = QLineEdit(self.frame_35)
        self.item_name_35.setObjectName(u"item_name_35")
        self.item_name_35.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_35 = QLineEdit(self.frame_35)
        self.item_reg_35.setObjectName(u"item_reg_35")
        self.item_reg_35.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_35 = QLineEdit(self.frame_35)
        self.item_index_35.setObjectName(u"item_index_35")
        self.item_index_35.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_35 = QLineEdit(self.frame_35)
        self.item_skip_35.setObjectName(u"item_skip_35")
        self.item_skip_35.setGeometry(QRect(840, 0, 61, 21))
        self.frame_36 = QFrame(self.tab_3)
        self.frame_36.setObjectName(u"frame_36")
        self.frame_36.setGeometry(QRect(0, 90, 911, 31))
        self.frame_36.setFrameShape(QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QFrame.Raised)
        self.item_name_36 = QLineEdit(self.frame_36)
        self.item_name_36.setObjectName(u"item_name_36")
        self.item_name_36.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_36 = QLineEdit(self.frame_36)
        self.item_reg_36.setObjectName(u"item_reg_36")
        self.item_reg_36.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_36 = QLineEdit(self.frame_36)
        self.item_index_36.setObjectName(u"item_index_36")
        self.item_index_36.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_36 = QLineEdit(self.frame_36)
        self.item_skip_36.setObjectName(u"item_skip_36")
        self.item_skip_36.setGeometry(QRect(840, 0, 61, 21))
        self.frame_37 = QFrame(self.tab_3)
        self.frame_37.setObjectName(u"frame_37")
        self.frame_37.setGeometry(QRect(0, 120, 911, 31))
        self.frame_37.setFrameShape(QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QFrame.Raised)
        self.item_name_37 = QLineEdit(self.frame_37)
        self.item_name_37.setObjectName(u"item_name_37")
        self.item_name_37.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_37 = QLineEdit(self.frame_37)
        self.item_reg_37.setObjectName(u"item_reg_37")
        self.item_reg_37.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_37 = QLineEdit(self.frame_37)
        self.item_index_37.setObjectName(u"item_index_37")
        self.item_index_37.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_37 = QLineEdit(self.frame_37)
        self.item_skip_37.setObjectName(u"item_skip_37")
        self.item_skip_37.setGeometry(QRect(840, 0, 61, 21))
        self.frame_38 = QFrame(self.tab_3)
        self.frame_38.setObjectName(u"frame_38")
        self.frame_38.setGeometry(QRect(0, 150, 911, 31))
        self.frame_38.setFrameShape(QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QFrame.Raised)
        self.item_name_38 = QLineEdit(self.frame_38)
        self.item_name_38.setObjectName(u"item_name_38")
        self.item_name_38.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_38 = QLineEdit(self.frame_38)
        self.item_reg_38.setObjectName(u"item_reg_38")
        self.item_reg_38.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_38 = QLineEdit(self.frame_38)
        self.item_index_38.setObjectName(u"item_index_38")
        self.item_index_38.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_38 = QLineEdit(self.frame_38)
        self.item_skip_38.setObjectName(u"item_skip_38")
        self.item_skip_38.setGeometry(QRect(840, 0, 61, 21))
        self.frame_39 = QFrame(self.tab_3)
        self.frame_39.setObjectName(u"frame_39")
        self.frame_39.setGeometry(QRect(0, 180, 911, 31))
        self.frame_39.setFrameShape(QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QFrame.Raised)
        self.item_name_39 = QLineEdit(self.frame_39)
        self.item_name_39.setObjectName(u"item_name_39")
        self.item_name_39.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_39 = QLineEdit(self.frame_39)
        self.item_reg_39.setObjectName(u"item_reg_39")
        self.item_reg_39.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_39 = QLineEdit(self.frame_39)
        self.item_index_39.setObjectName(u"item_index_39")
        self.item_index_39.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_39 = QLineEdit(self.frame_39)
        self.item_skip_39.setObjectName(u"item_skip_39")
        self.item_skip_39.setGeometry(QRect(840, 0, 61, 21))
        self.frame_40 = QFrame(self.tab_3)
        self.frame_40.setObjectName(u"frame_40")
        self.frame_40.setGeometry(QRect(0, 210, 911, 31))
        self.frame_40.setFrameShape(QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QFrame.Raised)
        self.item_name_40 = QLineEdit(self.frame_40)
        self.item_name_40.setObjectName(u"item_name_40")
        self.item_name_40.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_40 = QLineEdit(self.frame_40)
        self.item_reg_40.setObjectName(u"item_reg_40")
        self.item_reg_40.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_40 = QLineEdit(self.frame_40)
        self.item_index_40.setObjectName(u"item_index_40")
        self.item_index_40.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_40 = QLineEdit(self.frame_40)
        self.item_skip_40.setObjectName(u"item_skip_40")
        self.item_skip_40.setGeometry(QRect(840, 0, 61, 21))
        self.frame_41 = QFrame(self.tab_3)
        self.frame_41.setObjectName(u"frame_41")
        self.frame_41.setGeometry(QRect(0, 240, 911, 31))
        self.frame_41.setFrameShape(QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QFrame.Raised)
        self.item_name_41 = QLineEdit(self.frame_41)
        self.item_name_41.setObjectName(u"item_name_41")
        self.item_name_41.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_41 = QLineEdit(self.frame_41)
        self.item_reg_41.setObjectName(u"item_reg_41")
        self.item_reg_41.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_41 = QLineEdit(self.frame_41)
        self.item_index_41.setObjectName(u"item_index_41")
        self.item_index_41.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_41 = QLineEdit(self.frame_41)
        self.item_skip_41.setObjectName(u"item_skip_41")
        self.item_skip_41.setGeometry(QRect(840, 0, 61, 21))
        self.frame_42 = QFrame(self.tab_3)
        self.frame_42.setObjectName(u"frame_42")
        self.frame_42.setGeometry(QRect(0, 270, 911, 31))
        self.frame_42.setFrameShape(QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QFrame.Raised)
        self.item_name_42 = QLineEdit(self.frame_42)
        self.item_name_42.setObjectName(u"item_name_42")
        self.item_name_42.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_42 = QLineEdit(self.frame_42)
        self.item_reg_42.setObjectName(u"item_reg_42")
        self.item_reg_42.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_42 = QLineEdit(self.frame_42)
        self.item_index_42.setObjectName(u"item_index_42")
        self.item_index_42.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_42 = QLineEdit(self.frame_42)
        self.item_skip_42.setObjectName(u"item_skip_42")
        self.item_skip_42.setGeometry(QRect(840, 0, 61, 21))
        self.frame_43 = QFrame(self.tab_3)
        self.frame_43.setObjectName(u"frame_43")
        self.frame_43.setGeometry(QRect(0, 300, 911, 31))
        self.frame_43.setFrameShape(QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QFrame.Raised)
        self.item_name_43 = QLineEdit(self.frame_43)
        self.item_name_43.setObjectName(u"item_name_43")
        self.item_name_43.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_43 = QLineEdit(self.frame_43)
        self.item_reg_43.setObjectName(u"item_reg_43")
        self.item_reg_43.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_43 = QLineEdit(self.frame_43)
        self.item_index_43.setObjectName(u"item_index_43")
        self.item_index_43.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_43 = QLineEdit(self.frame_43)
        self.item_skip_43.setObjectName(u"item_skip_43")
        self.item_skip_43.setGeometry(QRect(840, 0, 61, 21))
        self.frame_44 = QFrame(self.tab_3)
        self.frame_44.setObjectName(u"frame_44")
        self.frame_44.setGeometry(QRect(0, 330, 911, 31))
        self.frame_44.setFrameShape(QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QFrame.Raised)
        self.item_name_44 = QLineEdit(self.frame_44)
        self.item_name_44.setObjectName(u"item_name_44")
        self.item_name_44.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_44 = QLineEdit(self.frame_44)
        self.item_reg_44.setObjectName(u"item_reg_44")
        self.item_reg_44.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_44 = QLineEdit(self.frame_44)
        self.item_index_44.setObjectName(u"item_index_44")
        self.item_index_44.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_44 = QLineEdit(self.frame_44)
        self.item_skip_44.setObjectName(u"item_skip_44")
        self.item_skip_44.setGeometry(QRect(840, 0, 61, 21))
        self.frame_45 = QFrame(self.tab_3)
        self.frame_45.setObjectName(u"frame_45")
        self.frame_45.setGeometry(QRect(0, 360, 911, 31))
        self.frame_45.setFrameShape(QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QFrame.Raised)
        self.item_name_45 = QLineEdit(self.frame_45)
        self.item_name_45.setObjectName(u"item_name_45")
        self.item_name_45.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_45 = QLineEdit(self.frame_45)
        self.item_reg_45.setObjectName(u"item_reg_45")
        self.item_reg_45.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_45 = QLineEdit(self.frame_45)
        self.item_index_45.setObjectName(u"item_index_45")
        self.item_index_45.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_45 = QLineEdit(self.frame_45)
        self.item_skip_45.setObjectName(u"item_skip_45")
        self.item_skip_45.setGeometry(QRect(840, 0, 61, 21))
        self.frame_46 = QFrame(self.tab_3)
        self.frame_46.setObjectName(u"frame_46")
        self.frame_46.setGeometry(QRect(0, 390, 911, 31))
        self.frame_46.setFrameShape(QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QFrame.Raised)
        self.item_name_46 = QLineEdit(self.frame_46)
        self.item_name_46.setObjectName(u"item_name_46")
        self.item_name_46.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_46 = QLineEdit(self.frame_46)
        self.item_reg_46.setObjectName(u"item_reg_46")
        self.item_reg_46.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_46 = QLineEdit(self.frame_46)
        self.item_index_46.setObjectName(u"item_index_46")
        self.item_index_46.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_46 = QLineEdit(self.frame_46)
        self.item_skip_46.setObjectName(u"item_skip_46")
        self.item_skip_46.setGeometry(QRect(840, 0, 61, 21))
        self.frame_47 = QFrame(self.tab_3)
        self.frame_47.setObjectName(u"frame_47")
        self.frame_47.setGeometry(QRect(0, 420, 911, 31))
        self.frame_47.setFrameShape(QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QFrame.Raised)
        self.item_name_47 = QLineEdit(self.frame_47)
        self.item_name_47.setObjectName(u"item_name_47")
        self.item_name_47.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_47 = QLineEdit(self.frame_47)
        self.item_reg_47.setObjectName(u"item_reg_47")
        self.item_reg_47.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_47 = QLineEdit(self.frame_47)
        self.item_index_47.setObjectName(u"item_index_47")
        self.item_index_47.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_47 = QLineEdit(self.frame_47)
        self.item_skip_47.setObjectName(u"item_skip_47")
        self.item_skip_47.setGeometry(QRect(840, 0, 61, 21))
        self.frame_48 = QFrame(self.tab_3)
        self.frame_48.setObjectName(u"frame_48")
        self.frame_48.setGeometry(QRect(0, 450, 911, 31))
        self.frame_48.setFrameShape(QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QFrame.Raised)
        self.item_name_48 = QLineEdit(self.frame_48)
        self.item_name_48.setObjectName(u"item_name_48")
        self.item_name_48.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_48 = QLineEdit(self.frame_48)
        self.item_reg_48.setObjectName(u"item_reg_48")
        self.item_reg_48.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_48 = QLineEdit(self.frame_48)
        self.item_index_48.setObjectName(u"item_index_48")
        self.item_index_48.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_48 = QLineEdit(self.frame_48)
        self.item_skip_48.setObjectName(u"item_skip_48")
        self.item_skip_48.setGeometry(QRect(840, 0, 61, 21))
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.tabWidget.addTab(self.tab_6, "")
        self.AlltoOneSheetCBtn = QCheckBox(self.centralwidget)
        self.AlltoOneSheetCBtn.setObjectName(u"AlltoOneSheetCBtn")
        self.AlltoOneSheetCBtn.setGeometry(QRect(660, 130, 151, 19))
        self.SheetName = QLineEdit(self.centralwidget)
        self.SheetName.setObjectName(u"SheetName")
        self.SheetName.setGeometry(QRect(820, 130, 161, 21))
        water_mainwd.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(water_mainwd)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 26))
        water_mainwd.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(water_mainwd)
        self.statusbar.setObjectName(u"statusbar")
        water_mainwd.setStatusBar(self.statusbar)

        self.retranslateUi(water_mainwd)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(water_mainwd)
    # setupUi

    def retranslateUi(self, water_mainwd):
        water_mainwd.setWindowTitle(QCoreApplication.translate("water_mainwd", u"water\u8c03\u8bd5\u7a97\u53e3", None))
        self.sel_log_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.sel_log_lbl.setText(QCoreApplication.translate("water_mainwd", u"water-core", None))
        self.label_18.setText(QCoreApplication.translate("water_mainwd", u"\u65e5\u5fd7\u9009\u62e9:", None))
        self.sel_tab_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.label_19.setText(QCoreApplication.translate("water_mainwd", u"\u8f93\u51fa\u5230\u8868\u683c:", None))
        self.sel_tab_lbl.setText(QCoreApplication.translate("water_mainwd", u"water-core", None))
        self.label_20.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u540d\u79f0", None))
        self.label_21.setText(QCoreApplication.translate("water_mainwd", u"\u5339\u914d\u8868\u8fbe\u5f0f", None))
        self.label_22.setText(QCoreApplication.translate("water_mainwd", u"\u5339\u914d\u5e8f\u53f7", None))
        self.label_23.setText(QCoreApplication.translate("water_mainwd", u"\u8d77\u59cb\u5339\u914d", None))
        self.label_24.setText(QCoreApplication.translate("water_mainwd", u"\u7ed3\u675f\u5339\u914d", None))
        self.start_filter.setText("")
        self.end_filter.setText("")
        self.label_25.setText(QCoreApplication.translate("water_mainwd", u"\u5339\u914d\u8df3\u8fc7\u6b21\u6570", None))
        self.load_setting_btn.setText(QCoreApplication.translate("water_mainwd", u"\u8f7d\u5165\u914d\u7f6e", None))
        self.dump_setting_btn.setText(QCoreApplication.translate("water_mainwd", u"\u5bfc\u51fa\u914d\u7f6e", None))
        self.exec_btn.setText(QCoreApplication.translate("water_mainwd", u"\u6267\u884c", None))
        self.clear_output_btn.setText(QCoreApplication.translate("water_mainwd", u"clear", None))
        self.clear_input_btn.setText(QCoreApplication.translate("water_mainwd", u"\u6e05\u7a7a\n"
"\u8f93\u5165", None))
        self.item_name_15.setText("")
        self.item_reg_15.setText("")
        self.item_index_15.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_15.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_6.setText("")
        self.item_reg_6.setText("")
        self.item_index_6.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_6.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_16.setText("")
        self.item_reg_16.setText("")
        self.item_index_16.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_16.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_9.setText("")
        self.item_reg_9.setText("")
        self.item_index_9.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_9.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_11.setText("")
        self.item_reg_11.setText("")
        self.item_index_11.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_11.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_1.setText("")
        self.item_reg_1.setText("")
        self.item_index_1.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_1.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_4.setText("")
        self.item_reg_4.setText("")
        self.item_index_4.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_4.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_5.setText("")
        self.item_reg_5.setText("")
        self.item_index_5.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_5.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_7.setText("")
        self.item_reg_7.setText("")
        self.item_index_7.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_7.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_12.setText("")
        self.item_reg_12.setText("")
        self.item_index_12.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_12.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_10.setText("")
        self.item_reg_10.setText("")
        self.item_index_10.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_10.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_14.setText("")
        self.item_reg_14.setText("")
        self.item_index_14.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_14.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_3.setText("")
        self.item_reg_3.setText("")
        self.item_index_3.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_3.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_13.setText("")
        self.item_reg_13.setText("")
        self.item_index_13.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_13.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_2.setText("")
        self.item_reg_2.setText("")
        self.item_index_2.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_2.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_8.setText("")
        self.item_reg_8.setText("")
        self.item_index_8.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_8.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("water_mainwd", u"1", None))
        self.item_name_17.setText("")
        self.item_reg_17.setText("")
        self.item_index_17.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_17.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_18.setText("")
        self.item_reg_18.setText("")
        self.item_index_18.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_18.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_19.setText("")
        self.item_reg_19.setText("")
        self.item_index_19.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_19.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_20.setText("")
        self.item_reg_20.setText("")
        self.item_index_20.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_20.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_21.setText("")
        self.item_reg_21.setText("")
        self.item_index_21.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_21.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_22.setText("")
        self.item_reg_22.setText("")
        self.item_index_22.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_22.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_23.setText("")
        self.item_reg_23.setText("")
        self.item_index_23.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_23.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_24.setText("")
        self.item_reg_24.setText("")
        self.item_index_24.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_24.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_25.setText("")
        self.item_reg_25.setText("")
        self.item_index_25.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_25.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_26.setText("")
        self.item_reg_26.setText("")
        self.item_index_26.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_26.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_27.setText("")
        self.item_reg_27.setText("")
        self.item_index_27.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_27.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_28.setText("")
        self.item_reg_28.setText("")
        self.item_index_28.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_28.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_29.setText("")
        self.item_reg_29.setText("")
        self.item_index_29.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_29.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_30.setText("")
        self.item_reg_30.setText("")
        self.item_index_30.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_30.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_31.setText("")
        self.item_reg_31.setText("")
        self.item_index_31.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_31.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_32.setText("")
        self.item_reg_32.setText("")
        self.item_index_32.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_32.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("water_mainwd", u"2", None))
        self.item_name_33.setText("")
        self.item_reg_33.setText("")
        self.item_index_33.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_33.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_34.setText("")
        self.item_reg_34.setText("")
        self.item_index_34.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_34.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_35.setText("")
        self.item_reg_35.setText("")
        self.item_index_35.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_35.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_36.setText("")
        self.item_reg_36.setText("")
        self.item_index_36.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_36.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_37.setText("")
        self.item_reg_37.setText("")
        self.item_index_37.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_37.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_38.setText("")
        self.item_reg_38.setText("")
        self.item_index_38.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_38.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_39.setText("")
        self.item_reg_39.setText("")
        self.item_index_39.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_39.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_40.setText("")
        self.item_reg_40.setText("")
        self.item_index_40.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_40.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_41.setText("")
        self.item_reg_41.setText("")
        self.item_index_41.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_41.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_42.setText("")
        self.item_reg_42.setText("")
        self.item_index_42.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_42.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_43.setText("")
        self.item_reg_43.setText("")
        self.item_index_43.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_43.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_44.setText("")
        self.item_reg_44.setText("")
        self.item_index_44.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_44.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_45.setText("")
        self.item_reg_45.setText("")
        self.item_index_45.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_45.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_46.setText("")
        self.item_reg_46.setText("")
        self.item_index_46.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_46.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_47.setText("")
        self.item_reg_47.setText("")
        self.item_index_47.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_47.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_48.setText("")
        self.item_reg_48.setText("")
        self.item_index_48.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_48.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("water_mainwd", u"3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("water_mainwd", u"4", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("water_mainwd", u"5", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("water_mainwd", u"6", None))
        self.AlltoOneSheetCBtn.setText(QCoreApplication.translate("water_mainwd", u"\u6c47\u603b\u5230\u7edf\u4e00Sheet:", None))
        self.SheetName.setText(QCoreApplication.translate("water_mainwd", u"Sheet01", None))
    # retranslateUi

