# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 5.15.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *


class Ui_water_mainwd(object):
    def setupUi(self, water_mainwd):
        if not water_mainwd.objectName():
            water_mainwd.setObjectName(u"water_mainwd")
        water_mainwd.resize(1000, 806)
        water_mainwd.setContextMenuPolicy(Qt.DefaultContextMenu)
        water_mainwd.setToolButtonStyle(Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(water_mainwd)
        self.centralwidget.setObjectName(u"centralwidget")
        self.sel_log_btn = QPushButton(self.centralwidget)
        self.sel_log_btn.setObjectName(u"sel_log_btn")
        self.sel_log_btn.setGeometry(QRect(120, 10, 21, 28))
        self.sel_log_lbl = QLineEdit(self.centralwidget)
        self.sel_log_lbl.setObjectName(u"sel_log_lbl")
        self.sel_log_lbl.setGeometry(QRect(160, 10, 771, 21))
        self.label_18 = QLabel(self.centralwidget)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(30, 10, 81, 21))
        self.sel_tab_btn = QPushButton(self.centralwidget)
        self.sel_tab_btn.setObjectName(u"sel_tab_btn")
        self.sel_tab_btn.setGeometry(QRect(120, 50, 21, 28))
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(30, 50, 81, 21))
        self.sel_tab_lbl = QLineEdit(self.centralwidget)
        self.sel_tab_lbl.setObjectName(u"sel_tab_lbl")
        self.sel_tab_lbl.setGeometry(QRect(160, 50, 771, 21))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 190, 911, 31))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.item_name_1 = QLineEdit(self.frame)
        self.item_name_1.setObjectName(u"item_name_1")
        self.item_name_1.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_1 = QLineEdit(self.frame)
        self.item_reg_1.setObjectName(u"item_reg_1")
        self.item_reg_1.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_1 = QLineEdit(self.frame)
        self.item_index_1.setObjectName(u"item_index_1")
        self.item_index_1.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_1 = QLineEdit(self.frame)
        self.item_skip_1.setObjectName(u"item_skip_1")
        self.item_skip_1.setGeometry(QRect(840, 0, 61, 21))
        self.label_20 = QLabel(self.centralwidget)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(70, 160, 81, 21))
        self.label_21 = QLabel(self.centralwidget)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(400, 160, 81, 21))
        self.label_22 = QLabel(self.centralwidget)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(750, 160, 81, 21))
        self.label_23 = QLabel(self.centralwidget)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(30, 90, 81, 21))
        self.label_24 = QLabel(self.centralwidget)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(30, 120, 81, 21))
        self.start_filter = QLineEdit(self.centralwidget)
        self.start_filter.setObjectName(u"start_filter")
        self.start_filter.setGeometry(QRect(120, 90, 511, 21))
        self.end_filter = QLineEdit(self.centralwidget)
        self.end_filter.setObjectName(u"end_filter")
        self.end_filter.setGeometry(QRect(120, 120, 511, 21))
        self.label_25 = QLabel(self.centralwidget)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(840, 160, 111, 21))
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 220, 911, 31))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.item_name_2 = QLineEdit(self.frame_2)
        self.item_name_2.setObjectName(u"item_name_2")
        self.item_name_2.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_2 = QLineEdit(self.frame_2)
        self.item_reg_2.setObjectName(u"item_reg_2")
        self.item_reg_2.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_2 = QLineEdit(self.frame_2)
        self.item_index_2.setObjectName(u"item_index_2")
        self.item_index_2.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_2 = QLineEdit(self.frame_2)
        self.item_skip_2.setObjectName(u"item_skip_2")
        self.item_skip_2.setGeometry(QRect(840, 0, 61, 21))
        self.frame_3 = QFrame(self.centralwidget)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(10, 250, 911, 31))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.item_name_3 = QLineEdit(self.frame_3)
        self.item_name_3.setObjectName(u"item_name_3")
        self.item_name_3.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_3 = QLineEdit(self.frame_3)
        self.item_reg_3.setObjectName(u"item_reg_3")
        self.item_reg_3.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_3 = QLineEdit(self.frame_3)
        self.item_index_3.setObjectName(u"item_index_3")
        self.item_index_3.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_3 = QLineEdit(self.frame_3)
        self.item_skip_3.setObjectName(u"item_skip_3")
        self.item_skip_3.setGeometry(QRect(840, 0, 61, 21))
        self.frame_4 = QFrame(self.centralwidget)
        self.frame_4.setObjectName(u"frame_4")
        self.frame_4.setGeometry(QRect(10, 280, 911, 31))
        self.frame_4.setFrameShape(QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QFrame.Raised)
        self.item_name_4 = QLineEdit(self.frame_4)
        self.item_name_4.setObjectName(u"item_name_4")
        self.item_name_4.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_4 = QLineEdit(self.frame_4)
        self.item_reg_4.setObjectName(u"item_reg_4")
        self.item_reg_4.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_4 = QLineEdit(self.frame_4)
        self.item_index_4.setObjectName(u"item_index_4")
        self.item_index_4.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_4 = QLineEdit(self.frame_4)
        self.item_skip_4.setObjectName(u"item_skip_4")
        self.item_skip_4.setGeometry(QRect(840, 0, 61, 21))
        self.frame_5 = QFrame(self.centralwidget)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(10, 310, 911, 31))
        self.frame_5.setFrameShape(QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.item_name_5 = QLineEdit(self.frame_5)
        self.item_name_5.setObjectName(u"item_name_5")
        self.item_name_5.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_5 = QLineEdit(self.frame_5)
        self.item_reg_5.setObjectName(u"item_reg_5")
        self.item_reg_5.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_5 = QLineEdit(self.frame_5)
        self.item_index_5.setObjectName(u"item_index_5")
        self.item_index_5.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_5 = QLineEdit(self.frame_5)
        self.item_skip_5.setObjectName(u"item_skip_5")
        self.item_skip_5.setGeometry(QRect(840, 0, 61, 21))
        self.frame_6 = QFrame(self.centralwidget)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(10, 340, 911, 31))
        self.frame_6.setFrameShape(QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.item_name_6 = QLineEdit(self.frame_6)
        self.item_name_6.setObjectName(u"item_name_6")
        self.item_name_6.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_6 = QLineEdit(self.frame_6)
        self.item_reg_6.setObjectName(u"item_reg_6")
        self.item_reg_6.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_6 = QLineEdit(self.frame_6)
        self.item_index_6.setObjectName(u"item_index_6")
        self.item_index_6.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_6 = QLineEdit(self.frame_6)
        self.item_skip_6.setObjectName(u"item_skip_6")
        self.item_skip_6.setGeometry(QRect(840, 0, 61, 21))
        self.frame_7 = QFrame(self.centralwidget)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(10, 370, 911, 31))
        self.frame_7.setFrameShape(QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.item_name_7 = QLineEdit(self.frame_7)
        self.item_name_7.setObjectName(u"item_name_7")
        self.item_name_7.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_7 = QLineEdit(self.frame_7)
        self.item_reg_7.setObjectName(u"item_reg_7")
        self.item_reg_7.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_7 = QLineEdit(self.frame_7)
        self.item_index_7.setObjectName(u"item_index_7")
        self.item_index_7.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_7 = QLineEdit(self.frame_7)
        self.item_skip_7.setObjectName(u"item_skip_7")
        self.item_skip_7.setGeometry(QRect(840, 0, 61, 21))
        self.frame_8 = QFrame(self.centralwidget)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(10, 400, 911, 31))
        self.frame_8.setFrameShape(QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.item_name_8 = QLineEdit(self.frame_8)
        self.item_name_8.setObjectName(u"item_name_8")
        self.item_name_8.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_8 = QLineEdit(self.frame_8)
        self.item_reg_8.setObjectName(u"item_reg_8")
        self.item_reg_8.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_8 = QLineEdit(self.frame_8)
        self.item_index_8.setObjectName(u"item_index_8")
        self.item_index_8.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_8 = QLineEdit(self.frame_8)
        self.item_skip_8.setObjectName(u"item_skip_8")
        self.item_skip_8.setGeometry(QRect(840, 0, 61, 21))
        self.frame_9 = QFrame(self.centralwidget)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(10, 430, 911, 31))
        self.frame_9.setFrameShape(QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.item_name_9 = QLineEdit(self.frame_9)
        self.item_name_9.setObjectName(u"item_name_9")
        self.item_name_9.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_9 = QLineEdit(self.frame_9)
        self.item_reg_9.setObjectName(u"item_reg_9")
        self.item_reg_9.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_9 = QLineEdit(self.frame_9)
        self.item_index_9.setObjectName(u"item_index_9")
        self.item_index_9.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_9 = QLineEdit(self.frame_9)
        self.item_skip_9.setObjectName(u"item_skip_9")
        self.item_skip_9.setGeometry(QRect(840, 0, 61, 21))
        self.frame_10 = QFrame(self.centralwidget)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(10, 460, 911, 31))
        self.frame_10.setFrameShape(QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.item_name_10 = QLineEdit(self.frame_10)
        self.item_name_10.setObjectName(u"item_name_10")
        self.item_name_10.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_10 = QLineEdit(self.frame_10)
        self.item_reg_10.setObjectName(u"item_reg_10")
        self.item_reg_10.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_10 = QLineEdit(self.frame_10)
        self.item_index_10.setObjectName(u"item_index_10")
        self.item_index_10.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_10 = QLineEdit(self.frame_10)
        self.item_skip_10.setObjectName(u"item_skip_10")
        self.item_skip_10.setGeometry(QRect(840, 0, 61, 21))
        self.frame_11 = QFrame(self.centralwidget)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(10, 490, 911, 31))
        self.frame_11.setFrameShape(QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.item_name_11 = QLineEdit(self.frame_11)
        self.item_name_11.setObjectName(u"item_name_11")
        self.item_name_11.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_11 = QLineEdit(self.frame_11)
        self.item_reg_11.setObjectName(u"item_reg_11")
        self.item_reg_11.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_11 = QLineEdit(self.frame_11)
        self.item_index_11.setObjectName(u"item_index_11")
        self.item_index_11.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_11 = QLineEdit(self.frame_11)
        self.item_skip_11.setObjectName(u"item_skip_11")
        self.item_skip_11.setGeometry(QRect(840, 0, 61, 21))
        self.frame_12 = QFrame(self.centralwidget)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(10, 520, 911, 31))
        self.frame_12.setFrameShape(QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.item_name_12 = QLineEdit(self.frame_12)
        self.item_name_12.setObjectName(u"item_name_12")
        self.item_name_12.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_12 = QLineEdit(self.frame_12)
        self.item_reg_12.setObjectName(u"item_reg_12")
        self.item_reg_12.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_12 = QLineEdit(self.frame_12)
        self.item_index_12.setObjectName(u"item_index_12")
        self.item_index_12.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_12 = QLineEdit(self.frame_12)
        self.item_skip_12.setObjectName(u"item_skip_12")
        self.item_skip_12.setGeometry(QRect(840, 0, 61, 21))
        self.frame_13 = QFrame(self.centralwidget)
        self.frame_13.setObjectName(u"frame_13")
        self.frame_13.setGeometry(QRect(10, 550, 911, 31))
        self.frame_13.setFrameShape(QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QFrame.Raised)
        self.item_name_13 = QLineEdit(self.frame_13)
        self.item_name_13.setObjectName(u"item_name_13")
        self.item_name_13.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_13 = QLineEdit(self.frame_13)
        self.item_reg_13.setObjectName(u"item_reg_13")
        self.item_reg_13.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_13 = QLineEdit(self.frame_13)
        self.item_index_13.setObjectName(u"item_index_13")
        self.item_index_13.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_13 = QLineEdit(self.frame_13)
        self.item_skip_13.setObjectName(u"item_skip_13")
        self.item_skip_13.setGeometry(QRect(840, 0, 61, 21))
        self.frame_14 = QFrame(self.centralwidget)
        self.frame_14.setObjectName(u"frame_14")
        self.frame_14.setGeometry(QRect(10, 580, 911, 31))
        self.frame_14.setFrameShape(QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QFrame.Raised)
        self.item_name_14 = QLineEdit(self.frame_14)
        self.item_name_14.setObjectName(u"item_name_14")
        self.item_name_14.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_14 = QLineEdit(self.frame_14)
        self.item_reg_14.setObjectName(u"item_reg_14")
        self.item_reg_14.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_14 = QLineEdit(self.frame_14)
        self.item_index_14.setObjectName(u"item_index_14")
        self.item_index_14.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_14 = QLineEdit(self.frame_14)
        self.item_skip_14.setObjectName(u"item_skip_14")
        self.item_skip_14.setGeometry(QRect(840, 0, 61, 21))
        self.frame_15 = QFrame(self.centralwidget)
        self.frame_15.setObjectName(u"frame_15")
        self.frame_15.setGeometry(QRect(10, 610, 911, 31))
        self.frame_15.setFrameShape(QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QFrame.Raised)
        self.item_name_15 = QLineEdit(self.frame_15)
        self.item_name_15.setObjectName(u"item_name_15")
        self.item_name_15.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_15 = QLineEdit(self.frame_15)
        self.item_reg_15.setObjectName(u"item_reg_15")
        self.item_reg_15.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_15 = QLineEdit(self.frame_15)
        self.item_index_15.setObjectName(u"item_index_15")
        self.item_index_15.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_15 = QLineEdit(self.frame_15)
        self.item_skip_15.setObjectName(u"item_skip_15")
        self.item_skip_15.setGeometry(QRect(840, 0, 61, 21))
        self.frame_16 = QFrame(self.centralwidget)
        self.frame_16.setObjectName(u"frame_16")
        self.frame_16.setGeometry(QRect(10, 640, 911, 31))
        self.frame_16.setFrameShape(QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QFrame.Raised)
        self.item_name_16 = QLineEdit(self.frame_16)
        self.item_name_16.setObjectName(u"item_name_16")
        self.item_name_16.setGeometry(QRect(20, 0, 151, 21))
        self.item_reg_16 = QLineEdit(self.frame_16)
        self.item_reg_16.setObjectName(u"item_reg_16")
        self.item_reg_16.setGeometry(QRect(200, 0, 511, 21))
        self.item_index_16 = QLineEdit(self.frame_16)
        self.item_index_16.setObjectName(u"item_index_16")
        self.item_index_16.setGeometry(QRect(750, 0, 61, 21))
        self.item_skip_16 = QLineEdit(self.frame_16)
        self.item_skip_16.setObjectName(u"item_skip_16")
        self.item_skip_16.setGeometry(QRect(840, 0, 61, 21))
        self.load_setting_btn = QPushButton(self.centralwidget)
        self.load_setting_btn.setObjectName(u"load_setting_btn")
        self.load_setting_btn.setGeometry(QRect(710, 90, 71, 28))
        self.dump_setting_btn = QPushButton(self.centralwidget)
        self.dump_setting_btn.setObjectName(u"dump_setting_btn")
        self.dump_setting_btn.setGeometry(QRect(820, 90, 71, 28))
        self.result_lbl = QTextBrowser(self.centralwidget)
        self.result_lbl.setObjectName(u"result_lbl")
        self.result_lbl.setGeometry(QRect(30, 670, 891, 81))
        self.exec_btn = QPushButton(self.centralwidget)
        self.exec_btn.setObjectName(u"exec_btn")
        self.exec_btn.setGeometry(QRect(930, 677, 61, 71))
        self.clear_output_btn = QPushButton(self.centralwidget)
        self.clear_output_btn.setObjectName(u"clear_output_btn")
        self.clear_output_btn.setGeometry(QRect(930, 630, 61, 31))
        self.clear_input_btn = QPushButton(self.centralwidget)
        self.clear_input_btn.setObjectName(u"clear_input_btn")
        self.clear_input_btn.setGeometry(QRect(940, 190, 51, 51))
        water_mainwd.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(water_mainwd)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1000, 26))
        water_mainwd.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(water_mainwd)
        self.statusbar.setObjectName(u"statusbar")
        water_mainwd.setStatusBar(self.statusbar)

        self.retranslateUi(water_mainwd)

        QMetaObject.connectSlotsByName(water_mainwd)
    # setupUi

    def retranslateUi(self, water_mainwd):
        water_mainwd.setWindowTitle(QCoreApplication.translate("water_mainwd", u"water\u8c03\u8bd5\u7a97\u53e3", None))
        self.sel_log_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.sel_log_lbl.setText(QCoreApplication.translate("water_mainwd", u"water-core", None))
        self.label_18.setText(QCoreApplication.translate("water_mainwd", u"\u65e5\u5fd7\u9009\u62e9:", None))
        self.sel_tab_btn.setText(QCoreApplication.translate("water_mainwd", u"...", None))
        self.label_19.setText(QCoreApplication.translate("water_mainwd", u"\u8f93\u51fa\u5230\u8868\u683c:", None))
        self.sel_tab_lbl.setText(QCoreApplication.translate("water_mainwd", u"water-core", None))
        self.item_name_1.setText("")
        self.item_reg_1.setText("")
        self.item_index_1.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_1.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.label_20.setText(QCoreApplication.translate("water_mainwd", u"\u5217\u540d\u79f0", None))
        self.label_21.setText(QCoreApplication.translate("water_mainwd", u"\u5339\u914d\u8868\u8fbe\u5f0f", None))
        self.label_22.setText(QCoreApplication.translate("water_mainwd", u"\u5339\u914d\u5e8f\u53f7", None))
        self.label_23.setText(QCoreApplication.translate("water_mainwd", u"\u8d77\u59cb\u5339\u914d", None))
        self.label_24.setText(QCoreApplication.translate("water_mainwd", u"\u7ed3\u675f\u5339\u914d", None))
        self.start_filter.setText("")
        self.end_filter.setText("")
        self.label_25.setText(QCoreApplication.translate("water_mainwd", u"\u5339\u914d\u8df3\u8fc7\u6b21\u6570", None))
        self.item_name_2.setText("")
        self.item_reg_2.setText("")
        self.item_index_2.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_2.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_3.setText("")
        self.item_reg_3.setText("")
        self.item_index_3.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_3.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_4.setText("")
        self.item_reg_4.setText("")
        self.item_index_4.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_4.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_5.setText("")
        self.item_reg_5.setText("")
        self.item_index_5.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_5.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_6.setText("")
        self.item_reg_6.setText("")
        self.item_index_6.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_6.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_7.setText("")
        self.item_reg_7.setText("")
        self.item_index_7.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_7.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_8.setText("")
        self.item_reg_8.setText("")
        self.item_index_8.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_8.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_9.setText("")
        self.item_reg_9.setText("")
        self.item_index_9.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_9.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_10.setText("")
        self.item_reg_10.setText("")
        self.item_index_10.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_10.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_11.setText("")
        self.item_reg_11.setText("")
        self.item_index_11.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_11.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_12.setText("")
        self.item_reg_12.setText("")
        self.item_index_12.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_12.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_13.setText("")
        self.item_reg_13.setText("")
        self.item_index_13.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_13.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_14.setText("")
        self.item_reg_14.setText("")
        self.item_index_14.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_14.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_15.setText("")
        self.item_reg_15.setText("")
        self.item_index_15.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_15.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_name_16.setText("")
        self.item_reg_16.setText("")
        self.item_index_16.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.item_skip_16.setText(QCoreApplication.translate("water_mainwd", u"0", None))
        self.load_setting_btn.setText(QCoreApplication.translate("water_mainwd", u"\u8f7d\u5165\u914d\u7f6e", None))
        self.dump_setting_btn.setText(QCoreApplication.translate("water_mainwd", u"\u5bfc\u51fa\u914d\u7f6e", None))
        self.exec_btn.setText(QCoreApplication.translate("water_mainwd", u"\u6267\u884c", None))
        self.clear_output_btn.setText(QCoreApplication.translate("water_mainwd", u"clear", None))
        self.clear_input_btn.setText(QCoreApplication.translate("water_mainwd", u"\u6e05\u7a7a\n"
"\u8f93\u5165", None))
    # retranslateUi

